obj_name: Mrk142
csv: data/Mrk142.csv
filters: [M2, W2, W1, SV, U, B, g, r, i, z]
wavelengths: [2246,1928,2600,5648,3465,4392,4770,6215,7545,8700]  # 观测波长(Å)
delay_ref: W2
gal_ref: M2
redshift: 0.0446
ebv: 0.0136
ICCF_TAU: [0.73, 0.80, 1.52, 0.81, 0.81, 1.05, 1.28, 1.07, 1.54, 0.81]  # 用列表替代字典
Nsamples: 1000
Nburnin: 500
priors:
  - [0.5, 2.0]      # A 的范围
  - [0.5, 2.0]      # B 的范围
  - [-25, 25]       # tau 的范围
  - [0.05, 5.0]     # Δ 的范围
  - [0.0, 10.0]     # σ 的范围
