obj_name: Mrk509
csv: data/Mrk509.csv
filters: [W2, M2, W1, U, B, V]
wavelengths: [1928,2236,2600,3467,4392,5468]  # 观测波长(Å)
delay_ref: W2
gal_ref: W2
redshift: 0.0341
ebv: 0.0493
ICCF_TAU: [0.73, 0.80, 1.52, 0.81, 0.81, 1.05, 1.28, 1.07, 1.54, 0.81]  # 用列表替代字典
Nsamples: 10000
Nburnin: 5000
priors:
  - [0.5, 2.0]      # A 的范围
  - [0.5, 2.0]      # B 的范围
  - [-25, 25]       # tau 的范围
  - [0.05, 5.0]     # Δ 的范围
  - [0.0, 10.0]     # σ 的范围
